# Generated by Django 5.1.4 on 2024-12-12 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0004_subscribe'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscribe',
            new_name='Subscription',
        ),
    ]
