# Generated by Django 5.1.4 on 2024-12-12 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0006_files'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Files',
        ),
        migrations.RemoveField(
            model_name='book',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='book',
            name='description',
        ),
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, default='default_path/default_image.jpg', null=True, upload_to='book_covers/'),
        ),
        migrations.AddField(
            model_name='book',
            name='file',
            field=models.FileField(default='default_path/default_file.pdf', upload_to='books/'),
        ),
        migrations.AddField(
            model_name='book',
            name='format',
            field=models.CharField(default='PDF', max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(default='Unknown Author', max_length=255),
        ),
    ]
