# Generated by Django 5.1.4 on 2024-12-13 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0007_delete_files_remove_book_cover_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(default='Unknown Genre', max_length=100),
        ),
    ]
