# Generated by Django 5.1.4 on 2024-12-13 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0008_book_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='cover_image',
        ),
        migrations.AddField(
            model_name='book',
            name='popular',
            field=models.BooleanField(default=False),
        ),
    ]
