# Generated by Django 5.1.4 on 2024-12-13 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0009_remove_book_cover_image_book_popular'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, default='default_path/default_image.jpg', null=True, upload_to='book_covers/'),
        ),
    ]
