# Generated by Django 5.1.4 on 2024-12-14 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0010_book_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(default='No description available.'),
        ),
    ]
