# Generated by Django 5.1.4 on 2024-12-14 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0011_book_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='authors/'),
        ),
    ]
